language: android

jdk:
  - oraclejdk8
  - oraclejdk7

android:
  components:
    - tools
    - tools # https://github.com/travis-ci/travis-ci/issues/6059
    - platform-tools
    - android-23
    - build-tools-23.0.3

sudo: required

before_install:
  - chmod +x gradlew
  
script:  
  - ./gradlew assembleRelease


